language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot2-webservice *
  - mkdir -p deploy
  - mv springboot2-webservice.zip deploy/springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-build
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true


notifications:
  email:
    recipients:
      - asdf016182@naver.com